import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { useState } from "react";
import img from "../public/undraw_digital_nomad_re_w8uy.svg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import RealEstate from "../public/realEstaetPhoto1 - Copy.png";
import pixldPhoto from "../public/PixldPhoto.png";
import jsTemplate from "../public/jsTemplate.png";
import youtubePhoto from "../public/YoutubePhoto.png";
import GptPhoto from "../public/GptPhoto.png";

import { Nav } from "./components/nav";
import { Hero } from "./components/hero";
import { Services } from "./components/services";
import { Projects } from "./components/projects";
export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Omar Portfolio</title>
        <meta
          name="description"
          content="Generated by Omar Portfolio Full stack developer"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          {/* NavBar */}
          <Nav setDarkMode={setDarkMode} darkMode={darkMode} />
          {/* End NavBar */}
          <Hero img={img} />
        </section>
        <Services design={design} code={code} consulting={consulting} />
        <Projects
          web1={RealEstate}
          web2={pixldPhoto}
          web3={jsTemplate}
          web4={youtubePhoto}
          web5={GptPhoto}
        />
      </main>
    </div>
  );
}
